// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    /* モジュールのソート
    */

    var autoSave;
    $("#sortable").sortable();
    $("#sortable").disableSelection();
    /* 記事タイトルの文字カウント
    */

    $("#entryTitle").keyup(function() {
      var counter;
      counter = $(this).val().length;
      $("#countUp").text(counter);
      if (counter === 0) {
        return $("#countUp").text("0");
      }
    });
    /* 見出し箇所のlocalStorage
    */

    $("#save_h").click(function() {
      var midashi_content, midashi_type;
      midashi_content = $("#midashi").val();
      midashi_type = $("input[name=midashi_type]:checked").val();
      localStorage.setItem("midashi", midashi_content);
      localStorage.setItem("midashi_type", midashi_type);
      return $(".sortarea").append('<div class="well3 ui-state-default"><' + midashi_type + '>' + midashi_content + '</' + midashi_type + '></div>');
    });
    $("#cancel_h").click(function() {
      $("#midashi").val("");
      return localStorage.removeItem("midashi");
    });
    (function() {
      if (localStorage.getItem("midashi")) {
        return $("#midashi").val(localStorage.getItem("midashi"));
      }
    })();
    /* 自動保存の数字を出すところ、1分毎に保存
    */

    return (autoSave = function() {
      var d;
      d = new Date();
      $("#save_message_h").text(d.getHours());
      $("#save_message_m").text(d.getMinutes());
      $("#save_message_s").text(d.getSeconds());
      return setTimeout(autoSave, 60000);
    })();
  });

}).call(this);
